import { getDbPool, sql } from '../db.js'

const rows = (result) => result.recordset
const asDate = (value) => value instanceof Date ? value.toISOString().slice(0, 10) : value
const asTime = (value) => typeof value === 'string' ? value.slice(0, 5) : value?.toISOString?.().slice(11, 16)
function normalizeSchedule(row) { return { ...row, start_time: asTime(row.start_time), end_time: asTime(row.end_time) } }
function normalizeRoom(row, bookings = []) { return { ...row, equipment: row.equipment ?? [], bookings } }
function normalizeEvent(row, registrations = []) { return { ...row, date: asDate(row.date), end_date: asDate(row.end_date), start_time: asTime(row.start_time), end_time: asTime(row.end_time), registrations } }
function normalizeAnnouncement(row) { return { ...row, date: asDate(row.date), expires: asDate(row.expires) } }
function normalizeAssignment(row) { return { ...row, assigned_date: asDate(row.assigned_date), deadline: asDate(row.deadline) } }
function notFound(message) { const error = new Error(message); error.statusCode = 404; return error }
function conflict(message) { const error = new Error(message); error.statusCode = 409; return error }

export async function listSchedules(filters = {}) {
  const request = (await getDbPool()).request()
  const conditions = []
  if (filters.course) { request.input('course', sql.VarChar(30), `%${filters.course}%`); conditions.push('course LIKE @course') }
  if (filters.day) { request.input('day', sql.VarChar(15), filters.day); conditions.push('day = @day') }
  if (filters.instructor) { request.input('instructor', sql.NVarChar(150), `%${filters.instructor}%`); conditions.push('instructor LIKE @instructor') }
  if (filters.room) { request.input('room', sql.VarChar(20), filters.room); conditions.push('room = @room') }
  const result = await request.query(`SELECT id, course, title, day, CONVERT(varchar(5), start_time, 108) AS start_time, CONVERT(varchar(5), end_time, 108) AS end_time, room, instructor, section FROM dbo.Schedules ${conditions.length ? `WHERE ${conditions.join(' AND ')}` : ''} ORDER BY CASE day WHEN 'Sunday' THEN 1 WHEN 'Monday' THEN 2 WHEN 'Tuesday' THEN 3 WHEN 'Wednesday' THEN 4 ELSE 5 END, start_time`)
  return rows(result).map(normalizeSchedule)
}
export async function getSchedule(id) { const request = (await getDbPool()).request().input('id', sql.VarChar(50), id); const result = await request.query("SELECT id, course, title, day, CONVERT(varchar(5), start_time, 108) AS start_time, CONVERT(varchar(5), end_time, 108) AS end_time, room, instructor, section FROM dbo.Schedules WHERE id = @id"); if (!result.recordset[0]) throw notFound('Schedule not found'); return normalizeSchedule(result.recordset[0]) }
export async function createSchedule(data) { const request = (await getDbPool()).request(); Object.entries(data).forEach(([key, value]) => request.input(key, key === 'title' || key === 'instructor' ? sql.NVarChar(200) : sql.VarChar(50), value)); const result = await request.query("INSERT INTO dbo.Schedules (id, course, title, day, start_time, end_time, room, instructor, section) OUTPUT INSERTED.id VALUES (@id, @course, @title, @day, TRY_CONVERT(time(0), @start_time), TRY_CONVERT(time(0), @end_time), @room, @instructor, @section)"); return getSchedule(result.recordset[0].id) }
export async function updateSchedule(id, data) { const request = (await getDbPool()).request().input('id', sql.VarChar(50), id); Object.entries(data).forEach(([key, value]) => request.input(key, key === 'title' || key === 'instructor' ? sql.NVarChar(200) : sql.VarChar(50), value)); const result = await request.query("UPDATE dbo.Schedules SET course=@course, title=@title, day=@day, start_time=TRY_CONVERT(time(0), @start_time), end_time=TRY_CONVERT(time(0), @end_time), room=@room, instructor=@instructor, section=@section WHERE id=@id"); if (!result.rowsAffected[0]) throw notFound('Schedule not found'); return getSchedule(id) }
export async function deleteSchedule(id) { const result = await (await getDbPool()).request().input('id', sql.VarChar(50), id).query('DELETE FROM dbo.Schedules WHERE id=@id'); if (!result.rowsAffected[0]) throw notFound('Schedule not found') }

async function roomEquipment(roomIds) { if (!roomIds.length) return new Map(); const request = (await getDbPool()).request(); request.input('ids', sql.VarChar(sql.MAX), roomIds.join(',')); const result = await request.query("SELECT room_id, equipment FROM dbo.RoomEquipment WHERE room_id IN (SELECT value FROM STRING_SPLIT(@ids, ','))"); return result.recordset.reduce((map, row) => map.set(row.room_id, [...(map.get(row.room_id) ?? []), row.equipment]), new Map()) }
export async function listRooms(filters = {}) { const request = (await getDbPool()).request(); const conditions = []; if (filters.room_number) { request.input('room_number', sql.VarChar(20), filters.room_number); conditions.push('r.room_number=@room_number') } if (filters.type) { request.input('type', sql.VarChar(30), filters.type); conditions.push('r.type=@type') } if (filters.floor) { request.input('floor', sql.TinyInt, Number(filters.floor)); conditions.push('r.floor=@floor') } if (filters.status) { request.input('status', sql.VarChar(20), filters.status); conditions.push('r.status=@status') } if (filters.capacity) { request.input('capacity', sql.Int, Number(filters.capacity)); conditions.push('r.capacity>=@capacity') } const result = await request.query(`SELECT r.id, r.room_number, r.type, r.capacity, r.floor, r.status FROM dbo.Rooms r ${conditions.length ? `WHERE ${conditions.join(' AND ')}` : ''} ORDER BY r.room_number`); const equipment = await roomEquipment(result.recordset.map((room) => room.id)); return result.recordset.map((room) => normalizeRoom({ ...room, equipment: equipment.get(room.id) ?? [] })) }
export async function getRoom(id) { const result = await listRooms({ room_number: id }); const room = result[0] ?? (await listRooms()).find((item) => item.id === id); if (!room) throw notFound('Room not found'); return { ...room, bookings: await listBookings(room.id) } }
export async function listBookings(roomId) { const request = (await getDbPool()).request(); if (roomId) request.input('room_id', sql.VarChar(50), roomId); const result = await request.query(`SELECT booking_id, room_id, booked_by, CONVERT(varchar(10), [date], 23) AS [date], CONVERT(varchar(5), start_time, 108) AS start_time, CONVERT(varchar(5), end_time, 108) AS end_time, purpose FROM dbo.RoomBookings ${roomId ? 'WHERE room_id=@room_id' : ''} ORDER BY [date], start_time`); return rows(result) }
export async function findAvailableRooms({ date, start_time, end_time, capacity, equipment = [] }) { const request = (await getDbPool()).request().input('date', sql.Date, date).input('start_time', sql.VarChar(5), start_time).input('end_time', sql.VarChar(5), end_time).input('capacity', sql.Int, Number(capacity ?? 0)); const result = await request.query("SELECT r.id, r.room_number, r.type, r.capacity, r.floor, r.status FROM dbo.Rooms r WHERE r.status='available' AND r.capacity>=@capacity AND NOT EXISTS (SELECT 1 FROM dbo.RoomBookings b WHERE b.room_id=r.id AND b.[date]=@date AND b.start_time < TRY_CONVERT(time(0), @end_time) AND b.end_time > TRY_CONVERT(time(0), @start_time)) ORDER BY r.capacity, r.room_number"); const equipmentMap = await roomEquipment(result.recordset.map((room) => room.id)); return result.recordset.filter((room) => equipment.every((needed) => (equipmentMap.get(room.id) ?? []).some((item) => item.toLowerCase() === needed.toLowerCase()))).map((room) => normalizeRoom({ ...room, equipment: equipmentMap.get(room.id) ?? [] })) }
export async function bookRoom(data) { const pool = await getDbPool(); const transaction = new sql.Transaction(pool); await transaction.begin(); try { const request = new sql.Request(transaction).input('room_id', sql.VarChar(50), data.room_id).input('room_number', sql.VarChar(20), data.room_number).input('date', sql.Date, data.date).input('start_time', sql.VarChar(5), data.start_time).input('end_time', sql.VarChar(5), data.end_time).input('booked_by', sql.NVarChar(150), data.booked_by).input('purpose', sql.NVarChar(250), data.purpose).input('booking_id', sql.VarChar(50), data.booking_id ?? `bk-${Date.now()}`); const result = await request.query("DECLARE @resolved_room_id VARCHAR(50) = COALESCE(@room_id, (SELECT id FROM dbo.Rooms WHERE room_number=@room_number)); IF @resolved_room_id IS NULL THROW 51000, 'Room not found', 1; IF TRY_CONVERT(time(0), @end_time) <= TRY_CONVERT(time(0), @start_time) THROW 51001, 'End time must be after start time', 1; IF EXISTS (SELECT 1 FROM dbo.RoomBookings WITH (UPDLOCK, HOLDLOCK) WHERE room_id=@resolved_room_id AND [date]=@date AND start_time < TRY_CONVERT(time(0), @end_time) AND end_time > TRY_CONVERT(time(0), @start_time)) THROW 51002, 'Room is already booked for that time', 1; INSERT INTO dbo.RoomBookings (booking_id, room_id, booked_by, [date], start_time, end_time, purpose) OUTPUT INSERTED.booking_id, INSERTED.room_id, INSERTED.booked_by, CONVERT(varchar(10), INSERTED.[date], 23) AS [date], CONVERT(varchar(5), INSERTED.start_time, 108) AS start_time, CONVERT(varchar(5), INSERTED.end_time, 108) AS end_time, INSERTED.purpose VALUES (@booking_id, @resolved_room_id, @booked_by, @date, TRY_CONVERT(time(0), @start_time), TRY_CONVERT(time(0), @end_time), @purpose)"); await transaction.commit(); return result.recordset[0] } catch (error) { await transaction.rollback(); if (error.number === 51000) throw notFound('Room not found'); if (error.number === 51001) { error.statusCode = 400; throw error } if (error.number === 51002) throw conflict('Room is already booked for that time'); throw error } }
export async function cancelBooking(bookingId) { const result = await (await getDbPool()).request().input('booking_id', sql.VarChar(50), bookingId).query('DELETE FROM dbo.RoomBookings WHERE booking_id=@booking_id'); if (!result.rowsAffected[0]) throw notFound('Booking not found') }

export async function listEvents(filters = {}) { const request = (await getDbPool()).request(); const conditions=[]; if(filters.date){request.input('date',sql.Date,filters.date);conditions.push('[date]=@date')} if(filters.status){request.input('status',sql.VarChar(20),filters.status);conditions.push('[status]=@status')} const result=await request.query(`SELECT id,name,description,CONVERT(varchar(10),[date],23) AS [date],CONVERT(varchar(5),start_time,108) AS start_time,CONVERT(varchar(5),end_time,108) AS end_time,CONVERT(varchar(10),end_date,23) AS end_date,venue,organizer,capacity,registered,status FROM dbo.Events ${conditions.length?'WHERE '+conditions.join(' AND '):''} ORDER BY [date],start_time`); const ids=result.recordset.map((event)=>event.id); const registrations=ids.length?await getRegistrations(ids):new Map(); return result.recordset.map((event)=>normalizeEvent(event,registrations.get(event.id)??[])) }
async function getRegistrations(eventIds) { const request=(await getDbPool()).request().input('ids',sql.VarChar(sql.MAX),eventIds.join(',')); const result=await request.query("SELECT student_id,event_id,name FROM dbo.EventRegistrations WHERE event_id IN (SELECT value FROM STRING_SPLIT(@ids, ','))"); return result.recordset.reduce((map,row)=>map.set(row.event_id,[...(map.get(row.event_id)??[]),{student_id:row.student_id,name:row.name}]),new Map()) }
export async function getEvent(id) { const result=await listEvents(); const event=result.find((item)=>item.id===id); if(!event)throw notFound('Event not found'); return event }
export async function createEvent(data) { const request=(await getDbPool()).request(); for(const [key,value] of Object.entries(data))request.input(key,key==='name'||key==='description'||key==='organizer'?sql.NVarChar(250):sql.VarChar(50),value); const result=await request.query("INSERT INTO dbo.Events (id,name,description,[date],start_time,end_time,end_date,venue,organizer,capacity,registered,status) OUTPUT INSERTED.id VALUES (@id,@name,@description,@date,TRY_CONVERT(time(0),@start_time),TRY_CONVERT(time(0),@end_time),@end_date,@venue,@organizer,@capacity,0,@status)"); return getEvent(result.recordset[0].id) }
export async function updateEvent(id,data) { const request=(await getDbPool()).request().input('id',sql.VarChar(50),id); for(const [key,value] of Object.entries(data))request.input(key,key==='name'||key==='description'||key==='organizer'?sql.NVarChar(250):sql.VarChar(50),value); const result=await request.query("UPDATE dbo.Events SET name=@name,description=@description,[date]=@date,start_time=TRY_CONVERT(time(0),@start_time),end_time=TRY_CONVERT(time(0),@end_time),end_date=@end_date,venue=@venue,organizer=@organizer,capacity=@capacity,status=@status WHERE id=@id"); if(!result.rowsAffected[0])throw notFound('Event not found'); return getEvent(id) }
export async function deleteEvent(id){const result=await(await getDbPool()).request().input('id',sql.VarChar(50),id).query('DELETE FROM dbo.Events WHERE id=@id');if(!result.rowsAffected[0])throw notFound('Event not found')}
export async function registerEvent(eventId,data){const pool=await getDbPool();const transaction=new sql.Transaction(pool);await transaction.begin();try{const request=new sql.Request(transaction).input('event_id',sql.VarChar(50),eventId).input('student_id',sql.VarChar(50),data.student_id).input('name',sql.NVarChar(150),data.name);const result=await request.query("DECLARE @capacity INT,@registered INT; SELECT @capacity=capacity,@registered=registered FROM dbo.Events WITH (UPDLOCK,HOLDLOCK) WHERE id=@event_id; IF @capacity IS NULL THROW 51010,'Event not found',1; IF EXISTS(SELECT 1 FROM dbo.EventRegistrations WHERE event_id=@event_id AND student_id=@student_id) THROW 51011,'Student is already registered',1; IF @registered>=@capacity THROW 51012,'Event is full',1; INSERT INTO dbo.EventRegistrations(student_id,event_id,name) VALUES(@student_id,@event_id,@name); UPDATE dbo.Events SET registered=registered+1,status=CASE WHEN registered+1>=capacity THEN 'full' ELSE status END WHERE id=@event_id; SELECT student_id,event_id,name FROM dbo.EventRegistrations WHERE event_id=@event_id AND student_id=@student_id");await transaction.commit();return result.recordset[0]}catch(error){await transaction.rollback();if(error.number===51010)throw notFound('Event not found');if(error.number===51011||error.number===51012)throw conflict(error.message);throw error}}
export async function cancelEventRegistration(eventId,studentId){const pool=await getDbPool();const transaction=new sql.Transaction(pool);await transaction.begin();try{const request=new sql.Request(transaction).input('event_id',sql.VarChar(50),eventId).input('student_id',sql.VarChar(50),studentId);const result=await request.query("IF NOT EXISTS(SELECT 1 FROM dbo.Events WHERE id=@event_id) THROW 51010,'Event not found',1; IF NOT EXISTS(SELECT 1 FROM dbo.EventRegistrations WHERE event_id=@event_id AND student_id=@student_id) THROW 51011,'Registration not found',1; DELETE FROM dbo.EventRegistrations WHERE event_id=@event_id AND student_id=@student_id; UPDATE dbo.Events SET registered=registered-1,status=CASE WHEN status='full' THEN 'upcoming' ELSE status END WHERE id=@event_id");await transaction.commit();return true}catch(error){await transaction.rollback();if(error.number===51010)throw notFound('Event not found');if(error.number===51011)throw notFound('Registration not found');throw error}}
export async function eventRegistrations(eventId){await getEvent(eventId);return (await getRegistrations([eventId])).get(eventId)??[]}

export async function listAnnouncements(filters={}){const request=(await getDbPool()).request();const conditions=[];if(filters.priority){request.input('priority',sql.VarChar(10),filters.priority);conditions.push('priority=@priority')}if(filters.active){conditions.push('expires>=CONVERT(date,GETDATE())')}const result=await request.query(`SELECT id,title,body,CONVERT(varchar(10),[date],23) AS [date],priority,posted_by,CONVERT(varchar(10),expires,23) AS expires FROM dbo.Announcements ${conditions.length?'WHERE '+conditions.join(' AND '):''} ORDER BY [date] DESC`);return result.recordset.map(normalizeAnnouncement)}
export async function getAnnouncement(id){const result=await listAnnouncements();const item=result.find((row)=>row.id===id);if(!item)throw notFound('Announcement not found');return item}
export async function createAnnouncement(data){const request=(await getDbPool()).request();for(const [key,value] of Object.entries(data))request.input(key,key==='title'||key==='body'||key==='posted_by'?sql.NVarChar(250):sql.VarChar(50),value);const result=await request.query("INSERT INTO dbo.Announcements(id,title,body,[date],priority,posted_by,expires) OUTPUT INSERTED.id VALUES(@id,@title,@body,@date,@priority,@posted_by,@expires)");return getAnnouncement(result.recordset[0].id)}
export async function updateAnnouncement(id,data){const request=(await getDbPool()).request().input('id',sql.VarChar(50),id);for(const [key,value] of Object.entries(data))request.input(key,key==='title'||key==='body'||key==='posted_by'?sql.NVarChar(250):sql.VarChar(50),value);const result=await request.query("UPDATE dbo.Announcements SET title=@title,body=@body,[date]=@date,priority=@priority,posted_by=@posted_by,expires=@expires WHERE id=@id");if(!result.rowsAffected[0])throw notFound('Announcement not found');return getAnnouncement(id)}
export async function deleteAnnouncement(id){const result=await(await getDbPool()).request().input('id',sql.VarChar(50),id).query('DELETE FROM dbo.Announcements WHERE id=@id');if(!result.rowsAffected[0])throw notFound('Announcement not found')}

export async function listAssignments(filters={}){const request=(await getDbPool()).request();const conditions=[];if(filters.course){request.input('course',sql.VarChar(30),filters.course);conditions.push('course=@course')}if(filters.status){request.input('status',sql.VarChar(15),filters.status);conditions.push('status=@status')}if(filters.upcoming){conditions.push('deadline>=CONVERT(date,GETDATE())')}const result=await request.query(`SELECT id,course,course_title,title,description,CONVERT(varchar(10),assigned_date,23) AS assigned_date,CONVERT(varchar(10),deadline,23) AS deadline,submission_platform,status,marks FROM dbo.Assignments ${conditions.length?'WHERE '+conditions.join(' AND '):''} ORDER BY deadline`);return result.recordset.map(normalizeAssignment)}
export async function getAssignment(id){const result=await listAssignments();const item=result.find((row)=>row.id===id);if(!item)throw notFound('Assignment not found');return item}
export async function createAssignment(data){const request=(await getDbPool()).request();for(const [key,value] of Object.entries(data))request.input(key,key==='course_title'||key==='title'||key==='description'||key==='submission_platform'?sql.NVarChar(250):key==='marks'?sql.Int:sql.VarChar(50),value);const result=await request.query("INSERT INTO dbo.Assignments(id,course,course_title,title,description,assigned_date,deadline,submission_platform,status,marks) OUTPUT INSERTED.id VALUES(@id,@course,@course_title,@title,@description,@assigned_date,@deadline,@submission_platform,@status,@marks)");return getAssignment(result.recordset[0].id)}
export async function updateAssignment(id,data){const request=(await getDbPool()).request().input('id',sql.VarChar(50),id);for(const [key,value] of Object.entries(data))request.input(key,key==='course_title'||key==='title'||key==='description'||key==='submission_platform'?sql.NVarChar(250):key==='marks'?sql.Int:sql.VarChar(50),value);const result=await request.query("UPDATE dbo.Assignments SET course=@course,course_title=@course_title,title=@title,description=@description,assigned_date=@assigned_date,deadline=@deadline,submission_platform=@submission_platform,status=@status,marks=@marks WHERE id=@id");if(!result.rowsAffected[0])throw notFound('Assignment not found');return getAssignment(id)}
export async function deleteAssignment(id){const result=await(await getDbPool()).request().input('id',sql.VarChar(50),id).query('DELETE FROM dbo.Assignments WHERE id=@id');if(!result.rowsAffected[0])throw notFound('Assignment not found')}
