import { AlertCircle, LoaderCircle, Pencil, Plus, RefreshCw, Search, Trash2, X } from 'lucide-react'
import { useEffect, useRef, useState, type FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ApiError, api } from '../api'
import type { ResourceMap, ResourceName } from '../types'

export type Field = { key: string; label: string; type?: 'text'|'textarea'|'date'|'time'|'number'|'select'|'tags'; options?: string[]; required?: boolean }
export type ResourceConfig<R extends ResourceName> = { resource: R; title: string; description: string; singular: string; fields: Field[]; primary: (item: ResourceMap[R]) => string; secondary: (item: ResourceMap[R]) => string; meta: (item: ResourceMap[R]) => string[] }
const emptyFor = (fields: Field[]) => Object.fromEntries(fields.map((field) => [field.key, field.type === 'number' ? 0 : field.type === 'tags' ? [] : '']))
export function ResourcePage<R extends ResourceName>({ config }: { config: ResourceConfig<R> }) {
  const client = useQueryClient(); const [search, setSearch] = useState(''); const [editing, setEditing] = useState<ResourceMap[R] | null>(null); const [formOpen, setFormOpen] = useState(false); const [form, setForm] = useState<Record<string, unknown>>(emptyFor(config.fields)); const dialog = useRef<HTMLDivElement>(null)
  const query = useQuery({ queryKey: [config.resource], queryFn: () => api.list(config.resource) })
  const save = useMutation({ mutationFn: () => editing ? api.update(config.resource, editing.id, form as Partial<ResourceMap[R]>) : api.create(config.resource, form as Omit<ResourceMap[R], 'id'>), onSuccess: () => { client.invalidateQueries({ queryKey: [config.resource] }); close() } })
  const remove = useMutation({ mutationFn: (id: string) => api.remove(config.resource, id), onSuccess: () => client.invalidateQueries({ queryKey: [config.resource] }) })
  const open = (item?: ResourceMap[R]) => { setEditing(item ?? null); setForm(item ? Object.fromEntries(config.fields.map((f) => [f.key, item[f.key as keyof typeof item]])) : emptyFor(config.fields)); setFormOpen(true) }
  const close = () => { setFormOpen(false); setEditing(null); save.reset() }
  useEffect(() => { if (formOpen) dialog.current?.querySelector<HTMLInputElement>('input,select,textarea')?.focus() }, [formOpen])
  const submit = (event: FormEvent) => { event.preventDefault(); save.mutate() }
  const items = query.data?.items.filter((item) => JSON.stringify(item).toLowerCase().includes(search.toLowerCase())) ?? []
  return <main className="page">
    <div className="page-heading"><div><span className="eyebrow">Campus records</span><h1>{config.title}</h1><p>{config.description}</p></div><button className="button" onClick={() => open()}><Plus size={17}/> Add {config.singular}</button></div>
    <div className="toolbar"><label className="search"><Search size={17}/><span className="sr-only">Search {config.title}</span><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder={`Search ${config.title.toLowerCase()}…`}/></label><span>{query.data?.total ?? 0} records</span></div>
    {query.isLoading ? <Loading/> : query.isError ? <ErrorState message={(query.error as Error).message} retry={() => query.refetch()}/> : items.length === 0 ? <Empty onAdd={() => open()} noun={config.singular}/> : <div className="resource-grid">{items.map((item) => <article className="resource-card card" key={item.id}><div className="resource-card-top"><span className="record-id">{item.id}</span><div><button className="icon-button" onClick={() => open(item)} aria-label={`Edit ${config.primary(item)}`}><Pencil size={16}/></button><button className="icon-button danger-icon" onClick={() => confirm(`Delete ${config.primary(item)}?`) && remove.mutate(item.id)} aria-label={`Delete ${config.primary(item)}`}><Trash2 size={16}/></button></div></div><h2>{config.primary(item)}</h2><p>{config.secondary(item)}</p><div className="meta-row">{config.meta(item).map((value) => <span key={value}>{value}</span>)}</div></article>)}</div>}
    {formOpen && <div className="modal-backdrop" role="presentation" onMouseDown={(e) => e.target === e.currentTarget && close()}><div className="modal card" role="dialog" aria-modal="true" aria-labelledby="form-title" ref={dialog}><div className="modal-head"><div><span className="eyebrow">{editing ? 'Update record' : 'New record'}</span><h2 id="form-title">{editing ? `Edit ${config.singular}` : `Add ${config.singular}`}</h2></div><button className="icon-button" onClick={close} aria-label="Close form"><X/></button></div><form onSubmit={submit}><div className="form-grid">{config.fields.map((field) => <FormField key={field.key} field={field} value={form[field.key]} onChange={(value) => setForm((old) => ({ ...old, [field.key]: value }))}/>)}</div>{save.isError && <div className="form-error" role="alert"><AlertCircle size={18}/><span>{save.error instanceof ApiError ? save.error.message : 'Unable to save this record.'}</span></div>}<div className="modal-actions"><button type="button" className="button secondary" onClick={close}>Cancel</button><button className="button" disabled={save.isPending}>{save.isPending ? <LoaderCircle className="spin" size={17}/> : null}{editing ? 'Save changes' : `Add ${config.singular}`}</button></div></form></div></div>}
  </main>
}
function FormField({ field, value, onChange }: { field: Field; value: unknown; onChange: (value: unknown) => void }) {
  const props = { id: field.key, required: field.required !== false, value: field.type === 'tags' ? (value as string[] ?? []).join(', ') : String(value ?? ''), onChange: (e: React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>) => onChange(field.type === 'number' ? Number(e.target.value) : field.type === 'tags' ? e.target.value.split(',').map(x => x.trim()).filter(Boolean) : e.target.value) }
  return <label className={field.type === 'textarea' ? 'field wide' : 'field'} htmlFor={field.key}><span>{field.label}</span>{field.type === 'textarea' ? <textarea {...props} rows={4}/> : field.type === 'select' ? <select {...props}><option value="">Choose…</option>{field.options?.map(x => <option key={x}>{x}</option>)}</select> : <input {...props} type={field.type === 'tags' ? 'text' : field.type ?? 'text'} placeholder={field.type === 'tags' ? 'projector, whiteboard, AC' : undefined}/>}</label>
}
export function Loading(){return <div className="state card"><LoaderCircle className="spin"/><strong>Loading campus data…</strong></div>}
export function ErrorState({message,retry}:{message:string;retry:()=>void}){return <div className="state card"><AlertCircle/><strong>Couldn’t load this workspace</strong><p>{message}</p><button className="button secondary" onClick={retry}><RefreshCw size={16}/> Try again</button></div>}
function Empty({onAdd,noun}:{onAdd:()=>void;noun:string}){return <div className="state card"><strong>No matching records</strong><p>Adjust your search or create a new {noun}.</p><button className="button secondary" onClick={onAdd}><Plus size={16}/> Add {noun}</button></div>}
