import { useState } from 'react'
import { Eye, Pencil, Search, Trash2, CalendarPlus } from 'lucide-react'
import { Badge } from '../components/common/Badge'
import { Modal, Field, FormActions } from '../components/common/Modal'
import { AnnouncementCard } from '../components/dashboard/AnnouncementCard'
import { AssignmentCard } from '../components/dashboard/AssignmentCard'
import { EventCard } from '../components/dashboard/EventCard'
import { ScheduleCard } from '../components/dashboard/ScheduleCard'
import { announcements as initialAnnouncements, assignments as initialAssignments, events as initialEvents, rooms as initialRooms, schedules as initialSchedules } from '../data/mockData'
import type { Announcement, Assignment, Event, Room, Schedule } from '../types/campus'

const today = '2026-09-06'
function Heading({ eyebrow, title, copy, action, onAction }: { eyebrow: string; title: string; copy: string; action: string; onAction: () => void }) { return <div className="page-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div><button className="primary-button" onClick={onAction}><CalendarPlus size={16} /> {action}</button></div> }
function Toolbar({ search, setSearch, children }: { search: string; setSearch: (value: string) => void; children?: React.ReactNode }) { return <div className="toolbar"><label className="search-box"><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search..." aria-label="Search" /></label>{children}</div> }
function Actions({ onView, onEdit, onDelete }: { onView: () => void; onEdit: () => void; onDelete: () => void }) { return <div className="row-actions"><button onClick={onView} aria-label="View" title="View"><Eye size={16} /></button><button onClick={onEdit} aria-label="Edit" title="Edit"><Pencil size={16} /></button><button onClick={onDelete} aria-label="Delete" title="Delete"><Trash2 size={16} /></button></div> }
function ReadModal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { return <Modal title={title} onClose={onClose}><div className="read-details">{children}</div></Modal> }
function TextFields({ values, setValues, fields }: { values: Record<string, string>; setValues: (values: Record<string, string>) => void; fields: Array<[string, string, string?]> }) { return <>{fields.map(([key, label, type]) => <Field key={key} label={label}><input required type={type ?? 'text'} value={values[key] ?? ''} onChange={(event) => setValues({ ...values, [key]: event.target.value })} /></Field>)}</> }

export function SchedulePage() {
  const [items, setItems] = useState(initialSchedules); const [search, setSearch] = useState(''); const [day, setDay] = useState('All days'); const [modal, setModal] = useState<{ kind: 'edit' | 'view'; item: Schedule } | { kind: 'add' } | null>(null)
  const filtered = items.filter((item) => (day === 'All days' || item.day === day) && `${item.course} ${item.title} ${item.instructor}`.toLowerCase().includes(search.toLowerCase()))
  const save = (values: Record<string, string>) => { const item = { id: values.id || `sch-${Date.now()}`, course: values.course, title: values.title, day: values.day, start_time: values.start_time, end_time: values.end_time, room: values.room, instructor: values.instructor, section: values.section }; setItems(items.some((entry) => entry.id === item.id) ? items.map((entry) => entry.id === item.id ? item : entry) : [...items, item]); setModal(null) }
  return <div><Heading eyebrow="Your week at a glance" title="Schedule" copy="Keep your classes and labs within reach." action="Add class" onAction={() => setModal({ kind: 'add' })} /><Toolbar search={search} setSearch={setSearch}><select value={day} onChange={(event) => setDay(event.target.value)}><option>All days</option>{['Sunday','Monday','Tuesday','Wednesday','Thursday'].map((value) => <option key={value}>{value}</option>)}</select></Toolbar><div className="management-list">{filtered.map((item) => <article className="manage-row" key={item.id}><ScheduleCard item={item} /><Actions onView={() => setModal({ kind: 'view', item })} onEdit={() => setModal({ kind: 'edit', item })} onDelete={() => setItems(items.filter((entry) => entry.id !== item.id))} /></article>)}</div>{modal && <ScheduleModal modal={modal} onClose={() => setModal(null)} onSave={save} />}</div>
}
function ScheduleModal({ modal, onClose, onSave }: { modal: { kind: 'edit' | 'view'; item: Schedule } | { kind: 'add' }; onClose: () => void; onSave: (values: Record<string, string>) => void }) { const item: Record<string, string> = modal.kind === 'add' ? { course:'', title:'', day:'Sunday', start_time:'', end_time:'', room:'', instructor:'', section:'' } : { course:modal.item.course, title:modal.item.title, day:modal.item.day, start_time:modal.item.start_time, end_time:modal.item.end_time, room:modal.item.room, instructor:modal.item.instructor, section:modal.item.section, id:modal.item.id }; const [values, setValues] = useState<Record<string,string>>(item); if (modal.kind === 'view') return <ReadModal title="Class details" onClose={onClose}><p><b>{item.course}</b> · Section {item.section}</p><h3>{item.title}</h3><p>{item.day}, {item.start_time} - {item.end_time}</p><p>Room {item.room} · {item.instructor}</p></ReadModal>; return <Modal title={modal.kind === 'add' ? 'Add class' : 'Edit class'} onClose={onClose}><form onSubmit={(event) => { event.preventDefault(); onSave(values) }}><TextFields values={values} setValues={setValues} fields={[['course','Course code'],['title','Course title'],['day','Day'],['start_time','Start time','time'],['end_time','End time','time'],['room','Room'],['instructor','Instructor'],['section','Section']]} /><FormActions onClose={onClose} /></form></Modal> }

export function RoomsPage() { const [items, setItems] = useState(initialRooms); const [search,setSearch]=useState(''); const [type,setType]=useState('All types'); const [status,setStatus]=useState('All statuses'); const [selected,setSelected]=useState<Room|null>(null); const filtered=items.filter((room)=>(type==='All types'||room.type===type)&&(status==='All statuses'||room.status===status)&&room.room_number.toLowerCase().includes(search.toLowerCase())); return <div><Heading eyebrow="Building 7 · Floor 7" title="Rooms" copy="Find the right space for your next session." action="Book room" onAction={() => setSelected(items[0])} /><Toolbar search={search} setSearch={setSearch}><select value={type} onChange={(e)=>setType(e.target.value)}><option>All types</option><option>classroom</option><option>lab</option><option>seminar hall</option></select><select value={status} onChange={(e)=>setStatus(e.target.value)}><option>All statuses</option><option>available</option><option>booked</option><option>maintenance</option></select></Toolbar><div className="rooms-listing management-grid">{filtered.map((room)=><article className="room-card" key={room.id}><div className="room-head"><div className="room-number">{room.room_number}</div><Badge tone={room.status==='available'?'green':room.status==='booked'?'amber':'red'}>{room.status}</Badge></div><h3>{room.type}</h3><p>Floor {room.floor} · Up to {room.capacity} people</p><div className="equipment">{room.equipment.map((e)=><span key={e}>{e}</span>)}</div><div className="card-actions"><button className="outline-button" onClick={()=>setSelected(room)}>Book room</button><Actions onView={()=>setSelected(room)} onEdit={()=>window.alert('Room editing is ready for local form wiring.')} onDelete={()=>setItems(items.filter((entry)=>entry.id!==room.id))}/></div></article>)}</div>{selected&&<RoomModal room={selected} onClose={()=>setSelected(null)} onBook={(booking)=>{setItems(items.map((room)=>room.id===selected.id?{...room,status:'booked',bookings:[...room.bookings,booking]}:room));setSelected(null)}} />}</div> }
function RoomModal({room,onClose,onBook}:{room:Room;onClose:()=>void;onBook:(booking:Room['bookings'][number])=>void}) { const [values,setValues]=useState<Record<string,string>>({date:today,start_time:'15:00',end_time:'17:00',booked_by:'Sakibul Hassan',purpose:''}); return <Modal title={`Book ${room.room_number}`} onClose={onClose}><div className="booking-summary"><b>{room.type}</b><span>Capacity {room.capacity} · {room.equipment.join(', ')}</span>{room.bookings.length>0&&<small>Existing: {room.bookings.map((b)=>`${b.date} ${b.start_time}-${b.end_time}`).join(', ')}</small>}</div><form onSubmit={(e)=>{e.preventDefault();onBook({booking_id:`bk-${Date.now()}`,...values} as Room['bookings'][number])}}><TextFields values={values} setValues={setValues} fields={[['date','Date','date'],['start_time','Start time','time'],['end_time','End time','time'],['booked_by','Booked by'],['purpose','Purpose']]} /><FormActions onClose={onClose} label="Confirm booking" /></form></Modal> }

export function EventsPage(){const [items,setItems]=useState(initialEvents);const [search,setSearch]=useState('');const [modal,setModal]=useState<Event|null|undefined>(undefined);const filtered=items.filter((e)=>`${e.name} ${e.venue} ${e.organizer}`.toLowerCase().includes(search.toLowerCase()));return <div><Heading eyebrow="Campus life" title="Events" copy="Discover what is happening around campus." action="Add event" onAction={()=>setModal(null)}/><Toolbar search={search} setSearch={setSearch}/><div className="events-listing management-list">{filtered.map((item)=><article className="manage-row" key={item.id}><EventCard item={item}/><div className="event-controls"><button className="outline-button" onClick={()=>setItems(items.map((e)=>e.id===item.id?{...e,registered:Math.min(e.capacity,e.registered+1)}:e))}>Register</button><button className="text-button" onClick={()=>setItems(items.map((e)=>e.id===item.id?{...e,registered:Math.max(0,e.registered-1)}:e))}>Cancel registration</button><Actions onView={()=>setModal(item)} onEdit={()=>setModal(item)} onDelete={()=>setItems(items.filter((e)=>e.id!==item.id))}/></div></article>)}</div>{modal!==undefined&&<EventModal item={modal} onClose={()=>setModal(undefined)} onSave={(item)=>{setItems(modal?items.map((e)=>e.id===item.id?item:e):[...items,item]);setModal(undefined)}}/>}</div>}
function EventModal({item,onClose,onSave}:{item:Event|null;onClose:()=>void;onSave:(item:Event)=>void}){const [values,setValues]=useState<Record<string,string>>(item?{name:item.name,description:item.description,date:item.date,start_time:item.start_time,end_time:item.end_time,end_date:item.end_date,venue:item.venue,organizer:item.organizer,capacity:String(item.capacity),registered:String(item.registered),status:item.status}:{name:'',description:'',date:today,start_time:'',end_time:'',end_date:today,venue:'',organizer:'',capacity:'50',registered:'0',status:'upcoming'});return <Modal title={item?'Edit event':'Add event'} onClose={onClose}><form onSubmit={(e)=>{e.preventDefault();onSave({...values,id:item?.id??`evt-${Date.now()}`,capacity:Number(values.capacity),registered:Number(values.registered),registrations:item?.registrations??[]} as Event)}}><TextFields values={values} setValues={setValues} fields={[['name','Event name'],['description','Description'],['date','Date','date'],['start_time','Start time','time'],['end_time','End time','time'],['end_date','End date','date'],['venue','Venue'],['organizer','Organizer'],['capacity','Capacity','number'],['status','Status']]}/><FormActions onClose={onClose} label={item?'Save event':'Add event'}/></form></Modal>}

export function AnnouncementsPage(){const [items,setItems]=useState(initialAnnouncements);const [search,setSearch]=useState('');const [modal,setModal]=useState<Announcement|null|undefined>(undefined);const filtered=items.filter((a)=>`${a.title} ${a.body}`.toLowerCase().includes(search.toLowerCase()));return <div><Heading eyebrow="Campus updates" title="Announcements" copy="The latest news from your department." action="Add announcement" onAction={()=>setModal(null)}/><Toolbar search={search} setSearch={setSearch}/><div className="announcements-listing management-list">{filtered.map((item)=><article className="manage-row" key={item.id}><AnnouncementCard item={item}/><Actions onView={()=>setModal(item)} onEdit={()=>setModal(item)} onDelete={()=>setItems(items.filter((a)=>a.id!==item.id))}/></article>)}</div>{modal!==undefined&&<AnnouncementModal item={modal} onClose={()=>setModal(undefined)} onSave={(item)=>{setItems(modal?items.map((a)=>a.id===item.id?item:a):[...items,item]);setModal(undefined)}}/>}</div>}
function AnnouncementModal({item,onClose,onSave}:{item:Announcement|null;onClose:()=>void;onSave:(item:Announcement)=>void}){const [values,setValues]=useState<Record<string,string>>(item?{title:item.title,body:item.body,date:item.date,priority:item.priority,posted_by:item.posted_by,expires:item.expires}:{title:'',body:'',date:today,priority:'medium',posted_by:'CSE Department',expires:today});return <Modal title={item?'Edit announcement':'Add announcement'} onClose={onClose}><form onSubmit={(e)=>{e.preventDefault();onSave({...values,id:item?.id??`ann-${Date.now()}`} as Announcement)}}><TextFields values={values} setValues={setValues} fields={[['title','Title'],['body','Body'],['date','Date','date'],['priority','Priority'],['posted_by','Posted by'],['expires','Expiry date','date']]}/><FormActions onClose={onClose} label="Publish"/></form></Modal>}

export function AssignmentsPage(){const [items,setItems]=useState(initialAssignments);const [search,setSearch]=useState('');const [status,setStatus]=useState('All statuses');const [sort,setSort]=useState('deadline');const [modal,setModal]=useState<Assignment|null|undefined>(undefined);const filtered=[...items].filter((a)=>(status==='All statuses'||a.status===status)&&`${a.course} ${a.title}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==='deadline'?a.deadline.localeCompare(b.deadline):a.course.localeCompare(b.course));return <div><Heading eyebrow="Academic workspace" title="Assignments" copy="Track every deadline in one place." action="Add assignment" onAction={()=>setModal(null)}/><Toolbar search={search} setSearch={setSearch}><select value={status} onChange={(e)=>setStatus(e.target.value)}><option>All statuses</option><option>pending</option><option>submitted</option><option>graded</option><option>late</option></select><select value={sort} onChange={(e)=>setSort(e.target.value)}><option value="deadline">Sort: deadline</option><option value="course">Sort: course</option></select></Toolbar><div className="assignments-listing management-list">{filtered.map((item)=><article className="manage-row" key={item.id}><AssignmentCard item={item}/><Actions onView={()=>setModal(item)} onEdit={()=>setModal(item)} onDelete={()=>setItems(items.filter((a)=>a.id!==item.id))}/></article>)}</div>{modal!==undefined&&<AssignmentModal item={modal} onClose={()=>setModal(undefined)} onSave={(item)=>{setItems(modal?items.map((a)=>a.id===item.id?item:a):[...items,item]);setModal(undefined)}}/>}</div>}
function AssignmentModal({item,onClose,onSave}:{item:Assignment|null;onClose:()=>void;onSave:(item:Assignment)=>void}){const [values,setValues]=useState<Record<string,string>>(item?{...item,marks:String(item.marks)}:{course:'',course_title:'',title:'',description:'',assigned_date:today,deadline:today,submission_platform:'Google Classroom',status:'pending',marks:'10'});return <Modal title={item?'Edit assignment':'Add assignment'} onClose={onClose}><form onSubmit={(e)=>{e.preventDefault();onSave({...values,id:item?.id??`asgn-${Date.now()}`,marks:Number(values.marks)} as Assignment)}}><TextFields values={values} setValues={setValues} fields={[['course','Course'],['course_title','Course title'],['title','Assignment title'],['description','Description'],['assigned_date','Assigned date','date'],['deadline','Deadline','date'],['submission_platform','Submission platform'],['status','Status'],['marks','Marks','number']]}/><FormActions onClose={onClose} label="Save assignment"/></form></Modal>}
