import { CalendarPlus, Check, Users, X } from 'lucide-react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState, type FormEvent } from 'react'
import { ApiError, api } from '../api'
import { ResourcePage, type ResourceConfig } from '../components/ResourcePage'
import { SelectionModal } from '../components/SelectionModal'
import type { Room } from '../types'
const config:ResourceConfig<'rooms'>={resource:'rooms',title:'Rooms',description:'Find equipped spaces and manage reservations.',singular:'room',fields:[{key:'room_number',label:'Room number'},{key:'type',label:'Type',type:'select',options:['classroom','lab','seminar']},{key:'capacity',label:'Capacity',type:'number'},{key:'equipment',label:'Equipment',type:'tags'},{key:'floor',label:'Floor',type:'number'},{key:'status',label:'Status',type:'select',options:['available','unavailable']}],primary:x=>x.room_number,secondary:x=>`${x.type} on floor ${x.floor}`,meta:x=>[`${x.capacity} seats`,...x.equipment,`${x.bookings.length} bookings`]}
export function Rooms(){const [selecting,setSelecting]=useState(false);const [booking,setBooking]=useState<Room|null>(null);const client=useQueryClient();const rooms=useQuery({queryKey:['rooms'],queryFn:()=>api.list('rooms')});const cancel=useMutation({mutationFn:({roomId,bookingId}:{roomId:string;bookingId:string})=>api.cancelBooking(roomId,bookingId),onSuccess:()=>client.invalidateQueries({queryKey:['rooms']})});const mine=rooms.data?.items.flatMap(room=>room.bookings.filter(item=>item.booked_by==='Sakibul Hassan').map(item=>({room,...item})))??[];const options=rooms.data?.items.map(room=>({id:room.id,title:`Room ${room.room_number}`,subtitle:`${room.type} · Floor ${room.floor}`,meta:[`${room.capacity} seats`,...room.equipment],disabled:room.status==='unavailable',badge:room.status}))??[];return <><ResourcePage config={config}/><section className="command-drawer glass-panel"><div><span className="eyebrow">My reservations</span><strong>{mine.length?`${mine.length} active booking${mine.length===1?'':'s'}`:'No active bookings'}</strong></div>{mine.map(item=><span key={item.booking_id}>{item.room.room_number} · {item.date} {item.start_time}–{item.end_time}<button onClick={()=>cancel.mutate({roomId:item.room.id,bookingId:item.booking_id})}>Cancel</button></span>)}</section>{booking&&<BookingModal room={booking} close={()=>setBooking(null)}/>}<button className="floating-action" onClick={()=>setSelecting(true)} disabled={rooms.isLoading}><CalendarPlus size={18}/> Book a room</button>{selecting&&<SelectionModal eyebrow="Room reservation" title="Choose a campus space" options={options} actionLabel="Continue to time" onSelect={id=>{setBooking(rooms.data?.items.find(room=>room.id===id)??null);setSelecting(false)}} onClose={()=>setSelecting(false)}/>}</>}
function BookingModal({room,close}:{room:Room;close:()=>void}){const client=useQueryClient();const [form,setForm]=useState({date:'2026-09-05',start_time:'14:00',end_time:'15:00',purpose:''});const mutation=useMutation({mutationFn:()=>api.book(room.id,form),onSuccess:()=>{client.invalidateQueries({queryKey:['rooms']});close()}});const submit=(event:FormEvent)=>{event.preventDefault();mutation.mutate()};return <div className="modal-backdrop select-backdrop"><div className="modal glass-panel" role="dialog" aria-modal="true"><div className="modal-head"><div><span className="eyebrow">Complete reservation</span><h2>Book room {room.room_number}</h2></div><button className="icon-button" onClick={close} aria-label="Close"><X/></button></div><form onSubmit={submit}><div className="room-highlight"><Users/><strong>{room.capacity} seats</strong><span>{room.equipment.join(' · ')}</span></div><div className="form-grid">{Object.entries(form).map(([key,value])=><label className={key==='purpose'?'field wide':'field'} key={key}><span>{key.replace('_',' ')}</span><input autoFocus={key==='date'} required type={key==='date'?'date':key.includes('time')?'time':'text'} value={value} onChange={event=>setForm({...form,[key]:event.target.value})}/></label>)}</div>{mutation.isError&&<div className="form-error" role="alert">{mutation.error instanceof ApiError?mutation.error.message:'Could not book this room.'}</div>}<div className="modal-actions"><button type="button" className="button secondary" onClick={close}>Back</button><button className="button" disabled={mutation.isPending}><Check size={16}/>Confirm booking</button></div></form></div></div>}
