"""initial persistence schema

Revision ID: 7cd073c14135
Revises: 
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7cd073c14135'
down_revision: Union[str, Sequence[str], None] = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_records')),
    sa.UniqueConstraint('operation', 'key', name='uq_idempotency_operation_key')
    )
    op.create_table('announcements',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.String(length=4000), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('posted_by', sa.String(length=200), nullable=False),
    sa.Column('expires', sa.Date(), nullable=False),
    sa.CheckConstraint('expires >= date', name=op.f('ck_announcements_valid_expiry')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcements'))
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcements_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_expires'), ['expires'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_priority'), ['priority'], unique=False)

    op.create_table('assignments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('course', sa.String(length=64), nullable=False),
    sa.Column('course_title', sa.String(length=300), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=3000), nullable=False),
    sa.Column('assigned_date', sa.Date(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('submission_platform', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('marks', sa.Float(), nullable=False),
    sa.CheckConstraint('deadline >= assigned_date', name=op.f('ck_assignments_valid_deadline')),
    sa.CheckConstraint('marks >= 0', name=op.f('ck_assignments_nonnegative_marks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignments'))
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignments_assigned_date'), ['assigned_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_course'), ['course'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_status'), ['status'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('venue', sa.String(length=200), nullable=False),
    sa.Column('organizer', sa.String(length=200), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('registered', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.CheckConstraint('capacity > 0', name=op.f('ck_events_positive_capacity')),
    sa.CheckConstraint('end_date >= date', name=op.f('ck_events_valid_date_range')),
    sa.CheckConstraint('registered >= 0 AND registered <= capacity', name=op.f('ck_events_valid_registered_count')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_venue'), ['venue'], unique=False)

    op.create_table('rooms',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('room_number', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.CheckConstraint('capacity > 0', name=op.f('ck_rooms_positive_capacity')),
    sa.CheckConstraint('floor >= 0', name=op.f('ck_rooms_nonnegative_floor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms'))
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_floor'), ['floor'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_room_number'), ['room_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_rooms_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_type'), ['type'], unique=False)

    op.create_table('schedules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('course', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('day', sa.String(length=16), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('room', sa.String(length=64), nullable=False),
    sa.Column('instructor', sa.String(length=200), nullable=False),
    sa.Column('section', sa.String(length=64), nullable=False),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_schedules_valid_time_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedules'))
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedules_course'), ['course'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_room'), ['room'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_section'), ['section'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_student_id'), ['student_id'], unique=True)

    op.create_table('bookings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('room_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('booked_by', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('purpose', sa.String(length=500), nullable=False),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_bookings_valid_time_range')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_bookings_room_id_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bookings_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings'))
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_date'), ['date'], unique=False)
        batch_op.create_index('ix_bookings_room_date_interval', ['room_id', 'date', 'start_time', 'end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_user_id'), ['user_id'], unique=False)

    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('course', sa.String(length=64), nullable=False),
    sa.Column('section', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_enrollments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollments')),
    sa.UniqueConstraint('user_id', 'course', 'section', name='uq_enrollment_user_course_section')
    )
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollments_course'), ['course'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_user_id'), ['user_id'], unique=False)

    op.create_table('registrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_registrations_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registrations')),
    sa.UniqueConstraint('event_id', 'student_id', name='uq_registration_event_student')
    )
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registrations_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_student_id'), ['student_id'], unique=False)

    op.create_table('room_equipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_equipment_room_id_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_equipment')),
    sa.UniqueConstraint('room_id', 'name', name='uq_room_equipment_room_name')
    )
    with op.batch_alter_table('room_equipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_equipment_room_id'), ['room_id'], unique=False)

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_equipment_room_id'))

    op.drop_table('room_equipment')
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registrations_student_id'))
        batch_op.drop_index(batch_op.f('ix_registrations_event_id'))

    op.drop_table('registrations')
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollments_user_id'))
        batch_op.drop_index(batch_op.f('ix_enrollments_course'))

    op.drop_table('enrollments')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_user_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_room_id'))
        batch_op.drop_index('ix_bookings_room_date_interval')
        batch_op.drop_index(batch_op.f('ix_bookings_date'))

    op.drop_table('bookings')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_student_id'))
        batch_op.drop_index(batch_op.f('ix_users_role'))

    op.drop_table('users')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_section'))
        batch_op.drop_index(batch_op.f('ix_schedules_room'))
        batch_op.drop_index(batch_op.f('ix_schedules_day'))
        batch_op.drop_index(batch_op.f('ix_schedules_course'))

    op.drop_table('schedules')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_type'))
        batch_op.drop_index(batch_op.f('ix_rooms_status'))
        batch_op.drop_index(batch_op.f('ix_rooms_room_number'))
        batch_op.drop_index(batch_op.f('ix_rooms_floor'))

    op.drop_table('rooms')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_venue'))
        batch_op.drop_index(batch_op.f('ix_events_status'))
        batch_op.drop_index(batch_op.f('ix_events_end_date'))
        batch_op.drop_index(batch_op.f('ix_events_date'))

    op.drop_table('events')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignments_status'))
        batch_op.drop_index(batch_op.f('ix_assignments_deadline'))
        batch_op.drop_index(batch_op.f('ix_assignments_course'))
        batch_op.drop_index(batch_op.f('ix_assignments_assigned_date'))

    op.drop_table('assignments')
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcements_priority'))
        batch_op.drop_index(batch_op.f('ix_announcements_expires'))
        batch_op.drop_index(batch_op.f('ix_announcements_date'))

    op.drop_table('announcements')
    op.drop_table('idempotency_records')
    # ### end Alembic commands ###
